-- OrcaSmart2 - Fase 4 - Schema MySQL/MariaDB
-- Dominio: Overrides e registros do usuario
-- Gerado em: 2026-07-09T23:01:29.063Z
-- Inventario base: 2026-07-09T22:40:43.616Z
-- Revisar antes de executar em producao.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS `tenant_componentes_bdi` (
  `id_tenant_componentes_bdi` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_componente` BIGINT NULL,
  `id_perfil_bdi` BIGINT NULL,
  `grupo` TEXT NULL,
  `codigo` TEXT NULL,
  `descricao` TEXT NULL,
  `base_legal` TEXT NULL,
  `percentual` DECIMAL(20,8) NULL,
  `incide_sobre` TEXT NULL,
  `ativo` BIGINT NULL,
  `ordem` BIGINT NULL,
  `observacoes` TEXT NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_componentes_bdi`),
  KEY `idx_tenant_componentes_bdi_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_composicoes` (
  `id_tenant_composicoes` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_composicao` BIGINT NULL,
  `codigo` TEXT NULL,
  `fonte` TEXT NULL,
  `formato` TEXT NULL,
  `descricao` TEXT NULL,
  `unidade` TEXT NULL,
  `id_grupo_comp` BIGINT NULL,
  `mes_referencia` TEXT NULL,
  `uf_referencia` TEXT NULL,
  `situacao_ref` TEXT NULL,
  `custo_unitario` DECIMAL(20,8) NULL,
  `fic` DECIMAL(20,8) NULL,
  `producao_equipe` DECIMAL(20,8) NULL,
  `unidade_producao` TEXT NULL,
  `situacao` TEXT NULL,
  `observacoes` TEXT NULL,
  `custo_horario_execucao` DECIMAL(20,8) NULL,
  `custo_unitario_execucao` DECIMAL(20,8) NULL,
  `custo_fic` DECIMAL(20,8) NULL,
  `subtotal_sicro` DECIMAL(20,8) NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_composicoes`),
  KEY `idx_tenant_composicoes_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_composicoes_secao_itens` (
  `id_tenant_composicoes_secao_itens` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_item_secao` BIGINT NULL,
  `id_composicao` BIGINT NULL,
  `id_secao` BIGINT NULL,
  `letra_secao` TEXT NULL,
  `codigo_item` TEXT NULL,
  `descricao` TEXT NULL,
  `quantidade` DECIMAL(20,8) NULL,
  `unidade` TEXT NULL,
  `util_operativa` DECIMAL(20,8) NULL,
  `util_improdutiva` DECIMAL(20,8) NULL,
  `custo_hp` DECIMAL(20,8) NULL,
  `custo_hi` DECIMAL(20,8) NULL,
  `preco_unitario` DECIMAL(20,8) NULL,
  `custo_total` DECIMAL(20,8) NULL,
  `cod_transporte` TEXT NULL,
  `cod_transp_ln` TEXT NULL,
  `cod_transp_rp` TEXT NULL,
  `cod_transp_p` TEXT NULL,
  `fit` DECIMAL(20,8) NULL,
  `dmt` DECIMAL(20,8) NULL,
  `ordem` BIGINT NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_composicoes_secao_itens`),
  KEY `idx_tenant_composicoes_secao_itens_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_composicoes_secoes` (
  `id_tenant_composicoes_secoes` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_secao` BIGINT NULL,
  `id_composicao` BIGINT NULL,
  `letra_secao` TEXT NULL,
  `nome_secao` TEXT NULL,
  `custo_total_secao` DECIMAL(20,8) NULL,
  `ordem` BIGINT NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_composicoes_secoes`),
  KEY `idx_tenant_composicoes_secoes_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_grupos_encargos` (
  `id_tenant_grupos_encargos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_grupo_enc` BIGINT NULL,
  `id_perfil` BIGINT NULL,
  `letra` TEXT NULL,
  `descricao` TEXT NULL,
  `total_grupo` DECIMAL(20,8) NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_grupos_encargos`),
  KEY `idx_tenant_grupos_encargos_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_insumos` (
  `id_tenant_insumos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_insumo` BIGINT NULL,
  `codigo_insumo` TEXT NULL,
  `descricao` TEXT NULL,
  `tipo_insumo` TEXT NULL,
  `id_unidade` BIGINT NULL,
  `id_grupo` BIGINT NULL,
  `origem` TEXT NULL,
  `encargos_aplicaveis` TEXT NULL,
  `situacao` TEXT NULL,
  `observacoes` TEXT NULL,
  `encargos_sociais_percentual` DECIMAL(20,8) NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_insumos`),
  KEY `idx_tenant_insumos_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_itens_composicao` (
  `id_tenant_itens_composicao` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_item` BIGINT NULL,
  `id_composicao` BIGINT NULL,
  `tipo_item` TEXT NULL,
  `codigo_item` TEXT NULL,
  `descricao` TEXT NULL,
  `unidade` TEXT NULL,
  `coeficiente` DECIMAL(20,8) NULL,
  `situacao_item` TEXT NULL,
  `preco_unitario` DECIMAL(20,8) NULL,
  `custo_parcial` DECIMAL(20,8) NULL,
  `ordem` BIGINT NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_itens_composicao`),
  KEY `idx_tenant_itens_composicao_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_itens_encargo` (
  `id_tenant_itens_encargo` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_item` BIGINT NULL,
  `id_grupo_enc` BIGINT NULL,
  `descricao` TEXT NULL,
  `base_legal` TEXT NULL,
  `percentual` DECIMAL(20,8) NULL,
  `observacoes` TEXT NULL,
  `ordem` BIGINT NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_itens_encargo`),
  KEY `idx_tenant_itens_encargo_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_perfis_bdi` (
  `id_tenant_perfis_bdi` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_perfil_bdi` BIGINT NULL,
  `nome_perfil` TEXT NULL,
  `tipo_obra` TEXT NULL,
  `regime_tributario` TEXT NULL,
  `descricao` TEXT NULL,
  `bdi_percentual` DECIMAL(20,8) NULL,
  `situacao` TEXT NULL,
  `usa_reforma_tributaria` BIGINT NULL,
  `vigencia` TEXT NULL,
  `observacoes` TEXT NULL,
  `ano_orcamento` BIGINT NULL,
  `ivaeq_percentual` DECIMAL(20,8) NULL,
  `iss_percentual_manual` DECIMAL(20,8) NULL,
  `id_orcamento_ivaeq` BIGINT NULL,
  `quartil` TEXT NULL,
  `cbs_percentual` DECIMAL(20,8) NULL,
  `ibs_percentual` DECIMAL(20,8) NULL,
  `fator_efetivo_ivaeq` DECIMAL(20,8) NULL,
  `percentual_mat_ivaeq` DECIMAL(20,8) NULL,
  `credito_bdi_ivaeq` DECIMAL(20,8) NULL,
  `regime_previdenciario` TEXT NULL,
  `simples_faixa` BIGINT NULL,
  `simples_faixa_label` TEXT NULL,
  `simples_receita_limite` DECIMAL(20,8) NULL,
  `simples_aliquota_efetiva` DECIMAL(20,8) NULL,
  `simples_irpj_percentual` DECIMAL(20,8) NULL,
  `simples_csll_percentual` DECIMAL(20,8) NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_perfis_bdi`),
  KEY `idx_tenant_perfis_bdi_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_perfis_encargos` (
  `id_tenant_perfis_encargos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_perfil` BIGINT NULL,
  `nome_perfil` TEXT NULL,
  `categoria` TEXT NULL,
  `regime` TEXT NULL,
  `uf_referencia` TEXT NULL,
  `id_data_base` BIGINT NULL,
  `descricao` TEXT NULL,
  `total_grupo_a` DECIMAL(20,8) NULL,
  `total_grupo_b` DECIMAL(20,8) NULL,
  `total_grupo_c` DECIMAL(20,8) NULL,
  `total_grupo_d` DECIMAL(20,8) NULL,
  `encargo_total` DECIMAL(20,8) NULL,
  `observacoes` TEXT NULL,
  `situacao` TEXT NULL,
  `vigencia` TEXT NULL,
  `fonte_referencia` TEXT NULL,
  `vigencia_inicio` TEXT NULL,
  `vigencia_fim` TEXT NULL,
  `encargo_original_percentual` DECIMAL(20,8) NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_perfis_encargos`),
  KEY `idx_tenant_perfis_encargos_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_precos_equipamentos` (
  `id_tenant_precos_equipamentos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_preco_eq` BIGINT NULL,
  `id_equip` BIGINT NULL,
  `id_data_base` BIGINT NULL,
  `id_fonte` BIGINT NULL,
  `uf_referencia` TEXT NULL,
  `preco_aquisicao` DECIMAL(20,8) NULL,
  `preco_combustivel` DECIMAL(20,8) NULL,
  `preco_operador_hora` DECIMAL(20,8) NULL,
  `custo_depreciacao` DECIMAL(20,8) NULL,
  `custo_juros` DECIMAL(20,8) NULL,
  `custo_manutencao` DECIMAL(20,8) NULL,
  `custo_materiais` DECIMAL(20,8) NULL,
  `custo_mao_obra` DECIMAL(20,8) NULL,
  `custo_imp_seguros` DECIMAL(20,8) NULL,
  `chp_calculado` DECIMAL(20,8) NULL,
  `chi_calculado` DECIMAL(20,8) NULL,
  `data_calculo` TEXT NULL,
  `observacoes` TEXT NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_precos_equipamentos`),
  KEY `idx_tenant_precos_equipamentos_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_precos_insumos` (
  `id_tenant_precos_insumos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_preco` BIGINT NULL,
  `id_insumo` BIGINT NULL,
  `id_data_base` BIGINT NULL,
  `id_fonte` BIGINT NULL,
  `uf_referencia` TEXT NULL,
  `preco_desonerado` DECIMAL(20,8) NULL,
  `preco_nao_desonerado` DECIMAL(20,8) NULL,
  `preco_referencia` DECIMAL(20,8) NULL,
  `cbs_percentual` DECIMAL(20,8) NULL,
  `ibs_percentual` DECIMAL(20,8) NULL,
  `is_percentual` DECIMAL(20,8) NULL,
  `iva_equivalente` DECIMAL(20,8) NULL,
  `preco_sem_tributos` DECIMAL(20,8) NULL,
  `data_coleta` TEXT NULL,
  `observacoes` TEXT NULL,
  `encargos_sociais_percentual` DECIMAL(20,8) NULL,
  `tenant_catalog_id` BIGINT NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_precos_insumos`),
  KEY `idx_tenant_precos_insumos_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_referential_overrides` (
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_override` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `domain` TEXT NOT NULL,
  `catalog_table` TEXT NOT NULL,
  `catalog_id` BIGINT NULL,
  `tenant_table` TEXT NULL,
  `tenant_rowid` BIGINT NULL,
  `action` TEXT NOT NULL,
  `impact_policy` VARCHAR(255) NOT NULL DEFAULT 'preserve',
  `payload_json` JSON NULL,
  `impact_json` JSON NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id_override`),
  KEY `idx_tenant_referential_overrides_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 1;
