-- OrcaSmart2 - Fase 4 - Schema MySQL/MariaDB
-- Dominio: Overrides e registros do usuario
-- Gerado em: 2026-07-09T23:58:00.493Z
-- Inventario base: 2026-07-09T22:40:43.616Z
-- Revisar antes de executar em producao.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS `tenant_componentes_bdi` (
  `id_tenant_componentes_bdi` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_componente` BIGINT UNSIGNED NULL,
  `id_perfil_bdi` BIGINT UNSIGNED NULL,
  `grupo` VARCHAR(120) NULL,
  `codigo` VARCHAR(120) NULL,
  `descricao` TEXT NULL,
  `base_legal` TEXT NULL,
  `percentual` DECIMAL(20,8) NULL,
  `incide_sobre` TEXT NULL,
  `ativo` BIGINT NULL,
  `ordem` BIGINT NULL,
  `observacoes` TEXT NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_componentes_bdi`),
  KEY `idx_tenant_componentes_bdi_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_composicoes` (
  `id_tenant_composicoes` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_composicao` BIGINT UNSIGNED NULL,
  `codigo` VARCHAR(120) NULL,
  `fonte` VARCHAR(120) NULL,
  `formato` VARCHAR(120) NULL,
  `descricao` TEXT NULL,
  `unidade` VARCHAR(120) NULL,
  `id_grupo_comp` BIGINT UNSIGNED NULL,
  `mes_referencia` VARCHAR(32) NULL,
  `uf_referencia` VARCHAR(32) NULL,
  `situacao_ref` VARCHAR(80) NULL,
  `custo_unitario` DECIMAL(20,8) NULL,
  `fic` DECIMAL(20,8) NULL,
  `producao_equipe` DECIMAL(20,8) NULL,
  `unidade_producao` VARCHAR(120) NULL,
  `situacao` VARCHAR(80) NULL,
  `observacoes` TEXT NULL,
  `custo_horario_execucao` DECIMAL(20,8) NULL,
  `custo_unitario_execucao` DECIMAL(20,8) NULL,
  `custo_fic` DECIMAL(20,8) NULL,
  `subtotal_sicro` DECIMAL(20,8) NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_composicoes`),
  KEY `idx_tenant_composicoes_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_composicoes_secao_itens` (
  `id_tenant_composicoes_secao_itens` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_item_secao` BIGINT UNSIGNED NULL,
  `id_composicao` BIGINT UNSIGNED NULL,
  `id_secao` BIGINT UNSIGNED NULL,
  `letra_secao` TEXT NULL,
  `codigo_item` VARCHAR(120) NULL,
  `descricao` TEXT NULL,
  `quantidade` DECIMAL(20,8) NULL,
  `unidade` VARCHAR(120) NULL,
  `util_operativa` DECIMAL(20,8) NULL,
  `util_improdutiva` DECIMAL(20,8) NULL,
  `custo_hp` DECIMAL(20,8) NULL,
  `custo_hi` DECIMAL(20,8) NULL,
  `preco_unitario` DECIMAL(20,8) NULL,
  `custo_total` DECIMAL(20,8) NULL,
  `cod_transporte` TEXT NULL,
  `cod_transp_ln` TEXT NULL,
  `cod_transp_rp` TEXT NULL,
  `cod_transp_p` TEXT NULL,
  `fit` DECIMAL(20,8) NULL,
  `dmt` DECIMAL(20,8) NULL,
  `ordem` BIGINT NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_composicoes_secao_itens`),
  KEY `idx_tenant_composicoes_secao_itens_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_composicoes_secoes` (
  `id_tenant_composicoes_secoes` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_secao` BIGINT UNSIGNED NULL,
  `id_composicao` BIGINT UNSIGNED NULL,
  `letra_secao` TEXT NULL,
  `nome_secao` VARCHAR(255) NULL,
  `custo_total_secao` DECIMAL(20,8) NULL,
  `ordem` BIGINT NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_composicoes_secoes`),
  KEY `idx_tenant_composicoes_secoes_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_grupos_encargos` (
  `id_tenant_grupos_encargos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_grupo_enc` BIGINT UNSIGNED NULL,
  `id_perfil` BIGINT UNSIGNED NULL,
  `letra` TEXT NULL,
  `descricao` TEXT NULL,
  `total_grupo` DECIMAL(20,8) NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_grupos_encargos`),
  KEY `idx_tenant_grupos_encargos_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_insumos` (
  `id_tenant_insumos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_insumo` BIGINT UNSIGNED NULL,
  `codigo_insumo` VARCHAR(120) NULL,
  `descricao` TEXT NULL,
  `tipo_insumo` VARCHAR(120) NULL,
  `id_unidade` BIGINT UNSIGNED NULL,
  `id_grupo` BIGINT UNSIGNED NULL,
  `origem` VARCHAR(120) NULL,
  `encargos_aplicaveis` TEXT NULL,
  `situacao` VARCHAR(80) NULL,
  `observacoes` TEXT NULL,
  `encargos_sociais_percentual` DECIMAL(20,8) NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_insumos`),
  KEY `idx_tenant_insumos_tenant_id` (`tenant_id`),
  KEY `idx_tenant_insumos_listagem` (`tenant_id`, `tenant_override_status`, `tipo_insumo`, `id_insumo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_itens_composicao` (
  `id_tenant_itens_composicao` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_item` BIGINT UNSIGNED NULL,
  `id_composicao` BIGINT UNSIGNED NULL,
  `tipo_item` VARCHAR(120) NULL,
  `codigo_item` VARCHAR(120) NULL,
  `descricao` TEXT NULL,
  `unidade` VARCHAR(120) NULL,
  `coeficiente` DECIMAL(20,8) NULL,
  `situacao_item` VARCHAR(80) NULL,
  `preco_unitario` DECIMAL(20,8) NULL,
  `custo_parcial` DECIMAL(20,8) NULL,
  `ordem` BIGINT NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_itens_composicao`),
  KEY `idx_tenant_itens_composicao_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_itens_encargo` (
  `id_tenant_itens_encargo` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_item` BIGINT UNSIGNED NULL,
  `id_grupo_enc` BIGINT UNSIGNED NULL,
  `descricao` TEXT NULL,
  `base_legal` TEXT NULL,
  `percentual` DECIMAL(20,8) NULL,
  `observacoes` TEXT NULL,
  `ordem` BIGINT NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_itens_encargo`),
  KEY `idx_tenant_itens_encargo_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_perfis_bdi` (
  `id_tenant_perfis_bdi` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_perfil_bdi` BIGINT UNSIGNED NULL,
  `nome_perfil` VARCHAR(255) NULL,
  `tipo_obra` VARCHAR(120) NULL,
  `regime_tributario` VARCHAR(80) NULL,
  `descricao` TEXT NULL,
  `bdi_percentual` DECIMAL(20,8) NULL,
  `situacao` VARCHAR(80) NULL,
  `usa_reforma_tributaria` BIGINT NULL,
  `vigencia` VARCHAR(32) NULL,
  `observacoes` TEXT NULL,
  `ano_orcamento` BIGINT NULL,
  `ivaeq_percentual` DECIMAL(20,8) NULL,
  `iss_percentual_manual` DECIMAL(20,8) NULL,
  `id_orcamento_ivaeq` BIGINT UNSIGNED NULL,
  `quartil` VARCHAR(120) NULL,
  `cbs_percentual` DECIMAL(20,8) NULL,
  `ibs_percentual` DECIMAL(20,8) NULL,
  `fator_efetivo_ivaeq` DECIMAL(20,8) NULL,
  `percentual_mat_ivaeq` DECIMAL(20,8) NULL,
  `credito_bdi_ivaeq` DECIMAL(20,8) NULL,
  `regime_previdenciario` VARCHAR(80) NULL,
  `simples_faixa` BIGINT NULL,
  `simples_faixa_label` TEXT NULL,
  `simples_receita_limite` DECIMAL(20,8) NULL,
  `simples_aliquota_efetiva` DECIMAL(20,8) NULL,
  `simples_irpj_percentual` DECIMAL(20,8) NULL,
  `simples_csll_percentual` DECIMAL(20,8) NULL,
  `redutor_setorial_ivaeq` DECIMAL(20,8) NULL,
  `redutor_governamental_ivaeq` DECIMAL(20,8) NULL,
  `usa_iva_manual` BIGINT NULL,
  `simples_rbt12` DECIMAL(20,8) NULL,
  `usa_simples_efetiva_manual` BIGINT NULL DEFAULT 0,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_perfis_bdi`),
  KEY `idx_tenant_perfis_bdi_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_perfis_encargos` (
  `id_tenant_perfis_encargos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_perfil` BIGINT UNSIGNED NULL,
  `nome_perfil` VARCHAR(255) NULL,
  `categoria` VARCHAR(80) NULL,
  `regime` VARCHAR(80) NULL,
  `uf_referencia` VARCHAR(32) NULL,
  `id_data_base` BIGINT UNSIGNED NULL,
  `descricao` TEXT NULL,
  `total_grupo_a` DECIMAL(20,8) NULL,
  `total_grupo_b` DECIMAL(20,8) NULL,
  `total_grupo_c` DECIMAL(20,8) NULL,
  `total_grupo_d` DECIMAL(20,8) NULL,
  `encargo_total` DECIMAL(20,8) NULL,
  `observacoes` TEXT NULL,
  `situacao` VARCHAR(80) NULL,
  `vigencia` VARCHAR(32) NULL,
  `fonte_referencia` VARCHAR(32) NULL,
  `vigencia_inicio` VARCHAR(32) NULL,
  `vigencia_fim` VARCHAR(32) NULL,
  `encargo_original_percentual` DECIMAL(20,8) NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_perfis_encargos`),
  KEY `idx_tenant_perfis_encargos_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_precos_equipamentos` (
  `id_tenant_precos_equipamentos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_preco_eq` BIGINT UNSIGNED NULL,
  `id_equip` BIGINT UNSIGNED NULL,
  `id_data_base` BIGINT UNSIGNED NULL,
  `id_fonte` BIGINT UNSIGNED NULL,
  `uf_referencia` VARCHAR(32) NULL,
  `preco_aquisicao` DECIMAL(20,8) NULL,
  `preco_combustivel` DECIMAL(20,8) NULL,
  `preco_operador_hora` DECIMAL(20,8) NULL,
  `custo_depreciacao` DECIMAL(20,8) NULL,
  `custo_juros` DECIMAL(20,8) NULL,
  `custo_manutencao` DECIMAL(20,8) NULL,
  `custo_materiais` DECIMAL(20,8) NULL,
  `custo_mao_obra` DECIMAL(20,8) NULL,
  `custo_imp_seguros` DECIMAL(20,8) NULL,
  `chp_calculado` DECIMAL(20,8) NULL,
  `chi_calculado` DECIMAL(20,8) NULL,
  `data_calculo` TEXT NULL,
  `observacoes` TEXT NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_precos_equipamentos`),
  KEY `idx_tenant_precos_equipamentos_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_precos_insumos` (
  `id_tenant_precos_insumos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_preco` BIGINT UNSIGNED NULL,
  `id_insumo` BIGINT UNSIGNED NULL,
  `id_data_base` BIGINT UNSIGNED NULL,
  `id_fonte` BIGINT UNSIGNED NULL,
  `uf_referencia` VARCHAR(32) NULL,
  `preco_desonerado` DECIMAL(20,8) NULL,
  `preco_nao_desonerado` DECIMAL(20,8) NULL,
  `preco_referencia` DECIMAL(20,8) NULL,
  `cbs_percentual` DECIMAL(20,8) NULL,
  `ibs_percentual` DECIMAL(20,8) NULL,
  `is_percentual` DECIMAL(20,8) NULL,
  `iva_equivalente` DECIMAL(20,8) NULL,
  `preco_sem_tributos` DECIMAL(20,8) NULL,
  `data_coleta` TEXT NULL,
  `observacoes` TEXT NULL,
  `encargos_sociais_percentual` DECIMAL(20,8) NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_precos_insumos`),
  KEY `idx_tenant_precos_insumos_tenant_id` (`tenant_id`),
  KEY `idx_tenant_precos_insumos_latest` (`tenant_id`, `id_insumo`, `id_preco`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_datas_base` (
  `id_tenant_datas_base` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_data_base` BIGINT UNSIGNED NULL,
  `mes` BIGINT NULL,
  `ano` BIGINT NULL,
  `data_referencia` VARCHAR(32) NULL,
  `descricao` TEXT NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_datas_base`),
  KEY `idx_tenant_datas_base_tenant_id` (`tenant_id`),
  KEY `idx_tenant_datas_base_catalog_id` (`tenant_catalog_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_unidades_medida` (
  `id_tenant_unidades_medida` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_unidade` BIGINT UNSIGNED NULL,
  `sigla` TEXT NULL,
  `descricao` TEXT NULL,
  `tipo_unidade` VARCHAR(120) NULL,
  `tenant_catalog_id` BIGINT UNSIGNED NULL,
  `tenant_override_action` VARCHAR(255) NOT NULL DEFAULT 'create',
  `tenant_override_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `tenant_created_at` DATETIME NULL,
  `tenant_updated_at` DATETIME NULL,
  PRIMARY KEY (`id_tenant_unidades_medida`),
  KEY `idx_tenant_unidades_medida_tenant_id` (`tenant_id`),
  KEY `idx_tenant_unidades_medida_catalog_id` (`tenant_catalog_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tenant_referential_overrides` (
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `id_override` BIGINT UNSIGNED NOT NULL,
  `domain` VARCHAR(120) NOT NULL,
  `catalog_table` VARCHAR(120) NOT NULL,
  `catalog_id` BIGINT UNSIGNED NULL,
  `tenant_table` VARCHAR(120) NULL,
  `tenant_rowid` BIGINT NULL,
  `action` VARCHAR(80) NOT NULL,
  `impact_policy` VARCHAR(255) NOT NULL DEFAULT 'preserve',
  `payload_json` JSON NULL,
  `impact_json` JSON NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`tenant_id`, `id_override`),
  KEY `idx_tenant_ref_overrides_lookup` (`tenant_id`, `domain`, `catalog_table`, `catalog_id`, `status`),
  KEY `idx_tenant_referential_overrides_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 1;
